/**
 * Shared types for the BudgetSplit API Worker.
 *
 * `Env` is hand-written rather than generated by `wrangler types` so it lives
 * in git next to the code that reads it — the same reasoning
 * `receipt-ocr-proxy/index.ts` applies to its own one-field `Env`.
 */

export interface Env {
  DB: D1Database;
  /**
   * One bucket, two prefixes: `backups/{user}/…` and `avatars/{user}`.
   *
   * **Optional.** R2 has to be enabled once on the dashboard before a bucket can
   * exist, so a first deploy may not have it — and sign-in and linking need no
   * storage whatsoever. The routes that do need it answer 503 with a message
   * naming the fix, rather than the whole Worker refusing to deploy.
   *
   * Preferred when present; `BLOBS` (KV) is the no-card fallback. See `storage.ts`.
   */
  FILES?: R2Bucket;
  /**
   * KV fallback for the same blobs. Part of the Workers free plan with no
   * payment method and no dashboard opt-in, which is exactly why it exists here.
   */
  BLOBS?: KVNamespace;
  /**
   * Cloudflare Email Sending. **Optional** — the binding requires Workers Paid,
   * so a free deployment has no `[[send_email]]` block at all and uses
   * `BREVO_API_KEY` instead. See `mailer.ts`.
   */
  EMAIL?: SendEmail;
  /** Set (via `wrangler secret`) to send through Brevo's free tier instead. */
  BREVO_API_KEY?: string;
  /**
   * The From address. With Brevo it is a single address verified by clicking a
   * link in that inbox; with Cloudflare it must be on an onboarded domain.
   */
  EMAIL_FROM: string;
  /** Deep link the magic-link email points back into, e.g. `budgetsplit://auth`. */
  APP_AUTH_URL: string;
  /** Deep link an invite bounces into, e.g. `budgetsplit:///link`. */
  APP_LINK_URL: string;
}

/** A row in `users`. */
export type UserRow = {
  id: string;
  email: string;
  name: string | null;
  /**
   * Self-declared and never verified — see `migrations/0002_profile.sql`. Only ever
   * returned to someone the user has linked with AND flagged as allowed to see it,
   * never to a lookup.
   */
  phone: string | null;
  /**
   * Either an R2 key (`avatars/{user_id}`, uploaded via `PUT /me/avatar`) or an
   * absolute `https://` URL the client set directly. Storing the key rather than
   * a baked-in absolute URL means the row survives the Worker moving from
   * `*.workers.dev` to a custom domain — `toUserDto` resolves it per request.
   */
  avatar_url: string | null;
  created_at: number;
  /**
   * Set when the account was closed (`DELETE /me`). The row survives because six
   * tables reference it and those rows are other people's records — see
   * `migrations/0010_account_deletion.sql`. Every identifying column has been
   * overwritten by then, so nothing here can be shown as a person; check this
   * before rendering one.
   */
  deleted_at?: number | null;
};

/** True when `users.avatar_url` points at our own R2 object rather than elsewhere. */
export const isAvatarKey = (value: string): boolean => value.startsWith('avatars/');

export const avatarKey = (userId: string): string => `avatars/${userId}`;

/** What `/me` and `/auth/verify` return — camelCase, unlike the DB row. */
export type UserDto = {
  id: string;
  email: string;
  name: string | null;
  phone: string | null;
  avatarUrl: string | null;
  createdAt: number;
};

/**
 * `origin` is the Worker's own origin for this request, used to turn a stored R2
 * key into a URL the app can actually fetch (`GET /me/avatar`, bearer-authed).
 */
export const toUserDto = (u: UserRow, origin: string): UserDto => ({
  id: u.id,
  email: u.email,
  name: u.name,
  phone: u.phone,
  avatarUrl: u.avatar_url && isAvatarKey(u.avatar_url) ? `${origin}/me/avatar` : u.avatar_url,
  createdAt: u.created_at,
});

export type BackupRow = {
  id: string;
  user_id: string;
  r2_key: string;
  size_bytes: number;
  created_at: number;
};

export type BackupDto = {
  id: string;
  sizeBytes: number;
  createdAt: number;
};

export const toBackupDto = (b: BackupRow): BackupDto => ({
  id: b.id,
  sizeBytes: b.size_bytes,
  createdAt: b.created_at,
});

// --- Linking (Stage B) -----------------------------------------------------

export type InviteRow = {
  token: string;
  from_user: string;
  expires_at: number;
  created_at: number;
  claimed_by: string | null;
  claimed_at: number | null;
  state: 'pending' | 'approved' | 'declined' | null;
};

/** A claim awaiting the sender's decision, as the sender sees it. */
export type PendingClaimDto = {
  token: string;
  claimedAt: number;
  /** Who claimed it — enough to recognise a person, and no more. */
  from: { id: string; name: string | null; email: string };
};

export type LinkRow = {
  id: string;
  user_a: string;
  user_b: string;
  created_at: number;
  share_phone_a: number;
  share_phone_b: number;
  /** Set when either side unlinked. A tombstone — see `0007_link_end.sql`. */
  ended_at: number | null;
  ended_by: string | null;
};

/**
 * A linked person, from the viewer's side.
 *
 * `phone` is present only when the *other* side has switched their disclosure on
 * — it is resolved per request rather than stored anywhere on the viewer's row,
 * so turning it off genuinely stops future reads.
 */
export type LinkDto = {
  id: string;
  createdAt: number;
  /** Whether *I* am showing my number to them. */
  sharingMyPhone: boolean;
  person: {
    id: string;
    name: string | null;
    email: string;
    phone: string | null;
    avatarUrl: string | null;
  };
};

/** Pairs are stored smaller-id-first so A→B and B→A cannot become two rows. */
export const orderPair = (x: string, y: string): [string, string] => (x < y ? [x, y] : [y, x]);

// --- Sync (Stage C) --------------------------------------------------------

/**
 * One sealed entry as it sits in D1.
 *
 * `ciphertext` is opaque here and stays opaque: the key is per-group and never
 * reaches this Worker. `version` is the one field deliberately in the clear —
 * compare-and-set has to work on a payload the server cannot read.
 */
export type SyncEntryRow = {
  version: number;
  ciphertext: string;
  author_user: string;
  is_deleted: number;
  updated_at: number;
};

export type SyncEntryDto = {
  entryId: string;
  version: number;
  ciphertext: string;
  author: string;
  isDeleted: boolean;
  updatedAt: number;
};
