import {
  AESEncryptionKey, AESSealedData, aesEncryptAsync, aesDecryptAsync, getRandomBytesAsync,
} from 'expo-crypto';
import { x25519 } from '@noble/curves/ed25519.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { base64ToBytes, bytesToBase64, hexToBytes, bytesToHex } from './bytes';

/**
 * Sealing a shared group's entries so the server holds bytes it cannot read.
 *
 * One key per group, generated by whoever shares it, wrapped once per member
 * **device**. The server stores wraps and sealed entries and never a key — which
 * is what makes "we cannot read it" on the Sync screen a fact rather than a
 * promise.
 *
 * The cipher is the same AES-256-GCM the backups use (`expo-crypto`, native), so
 * there is one cipher in the app and one place to change it.
 */

/** A group key, as it travels: base64, always wrapped, never stored bare. */
export type WrappedKey = string;

/** Generate a group key. Called once, by the device that shares the group. */
export async function newGroupKey(): Promise<Uint8Array> {
  return getRandomBytesAsync(32);
}

/**
 * Wrap a group key to one device, using only that device's PUBLIC key.
 *
 * Ephemeral-static X25519: a throwaway keypair is minted per wrap, ECDH'd against
 * the recipient's public key, and the resulting shared secret hashed into an AES
 * key. The ephemeral public key travels with the ciphertext; the ephemeral private
 * key is never stored and is unreachable the moment this returns.
 *
 * This is what makes the whole scheme asymmetric, and it buys three things:
 * the wrapper needs no secret of their own, so a public key is safe to publish;
 * nothing stored on the server can open anything; and each wrap has an
 * independent key, so compromising one device's wrap tells you nothing about the
 * others.
 */
export async function wrapGroupKey(groupKey: Uint8Array, devicePublicKey: string): Promise<WrappedKey> {
  const ephemeralSecret = x25519.utils.randomSecretKey();
  const ephemeralPublic = x25519.getPublicKey(ephemeralSecret);
  const kek = await AESEncryptionKey.import(
    kdf(x25519.getSharedSecret(ephemeralSecret, hexToBytes(devicePublicKey))),
  );
  const sealed = await aesEncryptAsync(groupKey, kek);
  // ephemeral public key || sealed. 32 bytes then the rest — a fixed prefix, so
  // reading it back needs no length field and no format to get wrong.
  return `${bytesToHex(ephemeralPublic)}.${await sealed.combined('base64')}`;
}

/**
 * Unwrap a group key with this device's own SECRET.
 *
 * Takes the secret rather than the public key, which is the shape the asymmetric
 * version requires and the previous symmetric one did not — a compile error at
 * every call site rather than a silent behaviour change, which is what it should
 * be for a change of this kind.
 */
export async function unwrapGroupKey(wrapped: WrappedKey, deviceSecret: Uint8Array): Promise<Uint8Array | null> {
  try {
    const dot = wrapped.indexOf('.');
    if (dot !== 64) return null; // not an ephemeral-static wrap
    const ephemeralPublic = hexToBytes(wrapped.slice(0, dot));
    const kek = await AESEncryptionKey.import(
      kdf(x25519.getSharedSecret(deviceSecret, ephemeralPublic)),
    );
    const sealed = AESSealedData.fromCombined(base64ToBytes(wrapped.slice(dot + 1)), {
      ivLength: 12, tagLength: 16,
    });
    return await aesDecryptAsync(sealed, kek);
  } catch {
    // A wrap meant for another device, or a tampered one. Null rather than a
    // throw: the caller's answer is the same either way — this group stays sealed.
    return null;
  }
}

/**
 * Shared secret to AES key.
 *
 * A raw X25519 output is a curve point, not a uniformly random key — the low bits
 * carry structure. Hashing is the minimum correct step, and it is what every
 * sealed-box construction does before handing the result to a cipher.
 */
function kdf(sharedSecret: Uint8Array): Uint8Array {
  return sha256(sharedSecret);
}

/**
 * What binds a sealed entry to its place in the world.
 *
 * Passed as GCM's additional authenticated data, so it is covered by the tag but
 * not encrypted. That is the point: the server can read and act on the version
 * while being unable to read the entry — which is what lets compare-and-set and
 * end-to-end encryption coexist at all.
 *
 * It also makes a sealed entry **non-transplantable**. Without this, a valid
 * ciphertext could be replayed under a different entry id or an older version and
 * would decrypt perfectly, letting someone roll a figure back to a previous value
 * and have every device accept it.
 */
function entryAad(groupId: string, entryId: string, version: number): Uint8Array {
  // Length-prefixed, not just delimited. A plain `a|b|c` join is ambiguous: group
  // `a` + entry `b|c` and group `a|b` + entry `c` produce identical bytes, so two
  // different entries become interchangeable — the exact thing this exists to
  // prevent. Ids are app-generated uuids and contain no pipe, so that flaw would
  // never have fired in practice and would have sat here looking correct.
  return new TextEncoder().encode(
    `${groupId.length}:${groupId}|${entryId.length}:${entryId}|${version}`,
  );
}

/** Seal one entry document for the wire. */
export async function sealEntry(
  entry: unknown,
  groupKey: Uint8Array,
  groupId: string,
  entryId: string,
  version: number,
): Promise<string> {
  const key = await AESEncryptionKey.import(groupKey);
  const sealed = await aesEncryptAsync(
    new TextEncoder().encode(JSON.stringify(entry)),
    key,
    { additionalData: entryAad(groupId, entryId, version) },
  );
  return await sealed.combined('base64');
}

/**
 * Open one entry. Null when it does not belong where it claims to.
 *
 * Null covers a wrong key, a tampered payload, AND an entry replayed under
 * another id or version — the AAD makes all three the same failure, which is
 * exactly right: in every case this is not an entry we should act on.
 */
export async function openEntry<T>(
  ciphertext: string,
  groupKey: Uint8Array,
  groupId: string,
  entryId: string,
  version: number,
): Promise<T | null> {
  try {
    const key = await AESEncryptionKey.import(groupKey);
    const sealed = AESSealedData.fromCombined(base64ToBytes(ciphertext), { ivLength: 12, tagLength: 16 });
    const bytes = await aesDecryptAsync(sealed, key, {
      additionalData: entryAad(groupId, entryId, version),
    });
    return JSON.parse(new TextDecoder().decode(bytes)) as T;
  } catch {
    return null;
  }
}

